use_frameworks!

target 'ISub_Example' do
  pod 'ISub', :path => '../'

  target 'ISub_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
